#!/bin/bash

echo "This script will help you update the Xcode project file after the directory restructuring."
echo "Please follow these steps in Xcode:"
echo ""
echo "1. Open the cursor-window.xcodeproj file in Xcode"
echo "2. In the Project Navigator, remove the references to:"
echo "   - cursor-window/cursor-window directory"
echo "   - cursor-window/readme.md"
echo "   - Any empty test directories"
echo ""
echo "3. Add the following files to the project:"
echo "   - cursor-window/Sources/App/Models/FrameProcessor.swift"
echo "   - cursor-window/Sources/App/Views/CapturePreview.swift"
echo ""
echo "4. Make sure all files are in the correct target"
echo ""
echo "5. Build the project to verify everything works"
echo ""
echo "6. Run the tests to ensure they still pass"
echo ""
echo "After completing these steps, you can commit the updated project file." 